export const Styles = theme => ({
    text:{
        color:'white',
        fontSize:18,
        backgroundColor:'#A93092',
        marginRight:'auto',
        padding:6,
    },
    urutanText:{
        borderBottom:'1px solid #A93092',
    },
    sem:{
        marginLeft:'Auto',
        textSize:'Bord'  
    },
    hubk:{
        color:'white',
        fontSize:18,
        backgroundColor:'#A93092',
        marginRight:'auto',
        padding:6,
    },
    kank:{
        color:'white',
        fontSize:18,
        backgroundColor:'#A93092',
        marginLeft:'auto',
        padding:6,
    },
});